ioengines: fix const-qualifier warning in fio_show_ioengine_help
strchr() on a const char * returns const char *, but sep was declared
as char *. Fix by duplicating the engine string with strdup() to get
a mutable copy, then operating on that copy. Also free the duplicated
string on all exit paths.

Fixes build error:
  ioengines.c:727:13: error: assignment discards 'const' qualifier
  from pointer target type [-Werror=discarded-qualifiers]